import js from "@eslint/js";
import importPlugin from "eslint-plugin-import-x";
import unicorn from "eslint-plugin-unicorn";
import sonarjs from "eslint-plugin-sonarjs";

export default [
  {
    ignores: ["coverage/**", "node_modules/**", "dist/**", "../.huashu-extract/**", "../assets/huashu/**", "../.claude/skills/impeccable/**", "../.specify/**", "**/*.umd.js", "**/*.min.js"],
  },
  js.configs.recommended,
  importPlugin.flatConfigs.recommended,
  unicorn.configs["flat/recommended"],
  sonarjs.configs.recommended,
  {
    // Globally disable rules that try to deep-parse plugin internals (fails on modern JS syntax)
    rules: {
      "import/namespace": "off",
      "import/default": "off",
      "import/no-named-as-default": "off",
      "import/no-named-as-default-member": "off",
    },
  },
  {
    files: ["src/**/*.js", "check-imports.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        process: "readonly",
        console: "readonly",
        setTimeout: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-empty": ["error", { "allowEmptyCatch": true }],
      "unicorn/filename-case": "off",
      "unicorn/prefer-module": "off",
      "unicorn/no-null": "off",
      "unicorn/prevent-abbreviations": "off",
      "unicorn/prefer-node-protocol": "off",
      "unicorn/import-style": "off",
      "unicorn/prefer-export-from": "off",
      "unicorn/catch-error-name": "off",
      "unicorn/text-encoding-identifier-case": "off",
      "unicorn/no-negated-condition": "off",
      "unicorn/prefer-string-replace-all": "off",
      "unicorn/prefer-number-properties": "off",
      "unicorn/consistent-function-scoping": "off",
      "unicorn/no-process-exit": "off",
      "unicorn/switch-case-braces": "off",
      "unicorn/prefer-at": "off",
      "unicorn/prefer-string-raw": "off",
      "unicorn/numeric-separators-style": "off",
      "unicorn/no-for-loop": "off",
      "unicorn/no-array-sort": "off",
      "unicorn/prefer-regexp-test": "off",
      "unicorn/no-nested-ternary": "off",
      "unicorn/no-array-for-each": "off",
      "unicorn/explicit-length-check": "off",
      "unicorn/name-replacements": "off",
      "unicorn/prefer-single-call": "off",
      "unicorn/no-for-each": "off",
      "unicorn/no-unsafe-string-replacement": "off",
      "unicorn/prefer-number-coercion": "off",
      "unicorn/prefer-simple-condition-first": "off",
      "unicorn/no-computed-property-existence-check": "off",
      "unicorn/no-unreadable-for-of-expression": "off",
      "unicorn/prefer-continue": "off",
      "unicorn/no-declarations-before-early-exit": "off",
      "unicorn/require-array-sort-compare": "off",
      "unicorn/no-break-in-nested-loop": "off",
      "unicorn/logical-assignment-operators": "off",
      "unicorn/no-duplicate-loops": "off",
      "unicorn/prefer-iterator-to-array": "off",
      "unicorn/consistent-boolean-name": "off",
      "unicorn/escape-case": "off",
      "unicorn/new-for-builtins": "off",
      "unicorn/no-abusive-eslint-disable": "off",
      "unicorn/no-array-reverse": "off",
      "unicorn/no-exports-in-scripts": "off",
      "unicorn/no-immediate-mutation": "off",
      "unicorn/no-incorrect-template-string-interpolation": "off",
      "unicorn/no-lonely-if": "off",
      "unicorn/no-return-array-push": "off",
      "unicorn/no-top-level-assignment-in-function": "off",
      "unicorn/no-unused-array-method-return": "off",
      "unicorn/prefer-await": "off",
      "unicorn/prefer-else-if": "off",
      "unicorn/prefer-includes-over-repeated-comparisons": "off",
      "unicorn/prefer-object-iterable-methods": "off",
      "unicorn/prefer-split-limit": "off",
      "unicorn/prefer-ternary": "off",
      "unicorn/prefer-unicode-code-point-escapes": "off",
      "sonarjs/no-nested-template-literals": "off",
      "sonarjs/no-nested-conditional": "off",
      "sonarjs/os-command": "off",
    },
  },
];
